### ISSUE TITLE
Missing .db File for the example IOC

### ISSUE THREAD

**Issue by eddybl** [Araneidae/picoharp#1]
Hey,

maybe I am misunderstanding how the example IOC should work. If I look at  `/docs/example_ioc/IOCApp/Db/ `
it seems like the IOC.db file is missing? Or how can I create the IOC.db file without the diamond specific build tools?

**Comment by Araneidae** [comment]
There should be a make rule for building `IOC.db` from `IOC.substitutions`.  I wonder if that's a DLS specific rule?  I know that our build process invokes [msi](https://epics.anl.gov/extensions/msi/index.php).  I get the following output during make:
```
Inflating database from ../IOC.substitutions using local Diamond rule
rm -f ../O.Common/IOC.db
msi -I..  -I/dls_sw/prod/R3.14.12.3/support/asyn/4-21/db -I/home/mga83/epics/picoharp/db -I/dls_sw/epics/R3.14.12.3/base/db -S../IOC.substitutions </dev/null > msi.tmp
mv msi.tmp ../O.Common/IOC.db
```

Drat.  We definitely have a `RULES.Dls` file in our EPICS `base/configure` directory, and it definitely got triggered above!  I think the relevant entry is this:
```
# translate a dbTemplate style substitution file.
$(COMMON_DIR)/%.db$(RAW): ../%.substitutions $(USES_TEMPLATE)
        @echo "Inflating database from $< using local Diamond rule"
        $(RM) $@
        $(DBDEPENDS_CMD)
        $(MSI) -I.. $(SYS_MSI_INCLUDES) -S$< <$(DEV_NULL) > msi.tmp
        $(MV) msi.tmp $@
```

I'm not sure what the best fix is.  Strictly speaking you don't need to run `msi` before loading the IOC, you can always apply the substitutions in the startup script instead, but that doesn't help with getting the example working!

**Comment by eddybl** [comment]
Would it be an option to add the resulting IOC.db just as a static file to the example ioc folder?

**Comment by Araneidae** [comment]
You can do that locally, but I'd be reluctant to do that to the published code: the IOC.db is a copy of `db/picoharp.db` with a number of substitutions, and you will need to apply those substitutions *somewhere*.  You're going to need to make changes, if only to the parameters, to get things working in your environment.

If you're not able to use `msi` to substitute the `picoharp.db` template then you can use `dbLoadRecords` to do the substitutions on the fly in the startup script instead.  However, I did think that `msi` was a standard EPICS way to do this.

I'm afraid it's safe to say that the example IOC is best used as an illustration of what needs to be defined rather than as a working example, and I'm unlikely to spend much time fixing this.  However, if you need more help getting the picoharp working for you, please do contact me.

**Comment by eddybl** [comment]
Hey,
yes, sorry my bad, I was actually thinking about adding the db/picoharp.db as a static file, not the IOC.db. But I managed to get the epicsdbbuilder running to create the picoharp.db, so I am good for now regarding the .db files.
